---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../release

patches:
  - target:
      kind: Application
      name: opentelemetry
    patch: |
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value:
          $values/environments/local/values.yaml
